name: pcsc-gscriptor
base: core18
adopt-info: pcsc-tools
summary: a GUI to send commands to a smart card using a batch file or stdin.
description: |
  gscriptor is a program that sends commands to a smart card using a batch file.

  The snap will auto-install the pcsc-daemon snap and automatically connect to
  the socket interface of the daemon

  You should manually connect the mount-observe interface (to quieten log spam,
  it will not limit any functionality if you do not connect it)

      snap connect pcsc-gscriptor:mount-observe

  To load batch files from external drives you also need to connect the removable-media
  interface

      snap connect pcsc-gscriptor:removable-media

  Icon made by Freepik (https://www.flaticon.com/authors/freepik)

grade: stable
confinement: strict

plugs:
  pcscd:
    interface: content
    content: pcscd-socket
    target: $SNAP_COMMON/pcscd
    default-provider: pcsc-daemon

architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: armhf
  - build-on: arm64

apps:
  pcsc-gscriptor:
    command: gscriptor
    extensions: [gnome-3-28]
    command-chain:
      - bin/debian-multiarch-triplet-provider-launch
      - bin/perl-launch
    environment:
      LANG: C.UTF-8
    plugs:
      - desktop
      - home
      - mount-observe
      - pcscd
      - removable-media
      - unity7
      - wayland
      - x11

parts:
  pcscd-libs:
    plugin: nil
    stage-snaps:
      - pcsc-daemon
    stage: # we only need the libs and headers
      - lib
      - include
    prime: # do not ship headers in binary snap, just libs
      - lib/libpcsclite*
      - -include
  pcsc-tools:
    source: https://salsa.debian.org/rousseau/pcsc-tools.git
    plugin: autotools
    after: [ pcscd-libs ]
    override-build: |
      snapcraftctl build
      #mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/doc/pcsc-tools
      #cp LICENCE $SNAPCRAFT_PART_INSTALL/usr/share/doc/pcsc-tools/
      # set version
      VERSION="$(grep AC_INIT configure.ac | sed 's/^.*\[//;s/\].*$//')"
      echo "setting version to $VERSION"
      snapcraftctl set-version $VERSION
    organize:
      $SNAPCRAFT_PART_SRC/LICENCE: usr/share/doc/pcsc-tools/LICENCE
    stage-packages:
      - libgetopt-complete-perl
      - libpcsc-perl
      - libglib-perl
      - libgtk3-perl
    stage-snaps:
      - debian-multiarch-triplet-provider-launch
      - perl-launch
  cleanup:
    after: [ pcsc-tools ]
    plugin: nil
    build-snaps: [ gnome-3-28-1804 ]
    override-prime: |
      set -eux
      cd /snap/gnome-3-28-1804/current
      find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;
      for CRUFT in bug lintian man; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
      done
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
